"use client";

import type { NoteStyle } from "../types";
import {
  DownArrow,
  VisualShell,
  nodeClass,
  safeItems,
} from "./shared";

export default function FlowchartBlock({
  title,
  items,
  style,
}: {
  title?: string;
  items?: string[];
  style: NoteStyle;
}) {
  const rawNodes = safeItems(items);

  if (!rawNodes.length) return null;

  // Remove accidental standalone arrow/connector nodes generated by AI.
  const nodes = rawNodes.filter(
    (item) =>
      !/^(↓|↑|→|←|↔|->|-->|=>|→+|↓+)$/.test(
        item.trim()
      )
  );

  if (!nodes.length) return null;

  return (
    <VisualShell title={title} label="Flow">
      <div className="mx-auto w-full max-w-[680px]">
        <div className="flex flex-col items-stretch">
          {nodes.map((item, index) => (
            <div
              key={`${item}-${index}`}
              className="flex flex-col items-center"
            >
              <div
                className={[
                  "w-full rounded-[16px] border px-4 py-3.5 text-center",
                  "text-[13px] font-bold leading-6 sm:px-5 sm:text-[14px]",
                  nodeClass(style, index),
                ].join(" ")}
              >
                {item}
              </div>

              {index < nodes.length - 1 ? (
                <div className="flex h-9 items-center justify-center">
                  <DownArrow />
                </div>
              ) : null}
            </div>
          ))}
        </div>

        <div className="mt-4 rounded-[12px] border border-black/[0.06] bg-black/[0.025] px-3 py-2.5 text-center font-[cursive] text-[12px] leading-5 text-[#64748B]">
          Follow the steps from top to bottom.
        </div>
      </div>
    </VisualShell>
  );
}
